GET http://localhost:3001/api/blogs HTTP/1.1

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImltYW1zdCIsImlkIjoiNjZlYWExMzZlNGUyMDA4MzM5MGYzZDhkIiwiaWF0IjoxNzI2ODIzOTEzfQ._57G4tv297DttZXk23hFhpc625l2vYDPYbmUFUB-yLI

{
  "title": "The Easiest Way to Success Before You Born",
  "author": "Imam Setiawan",
  "url": "http://google.co.id",
  "likes": 79,
  "userId": "66eaa136e4e20083390f3d8d"
}